### ISSUE TITLE
Switch between dark and light theme based on system settings

### ISSUE THREAD

**Issue by trosel** [cabal-club/cabal-desktop#169]
I know that themes haven't even been implemented yet (https://github.com/cabal-club/cabal-desktop/issues/67), but this seems to be the way users are going now.

Speaking completely for myself, I prefer to have the system switch between light and dark modes based on time of day.

**Comment by okdistribute** [comment]
Thanks @trosel .. PRs welcome. I think this would get backburnered because many of the volunteers are finishing up classes/focusing on family, and the current implementation is not compatible with the cli version which is an issue -- we need to integrate #168. I am seeing the volunteers collectively focusing crucial bug fixes & refactors currently to get a suitable cabal-browser implementation.

**Comment by trosel** [comment]
@okdistribute Thanks for the info!

> I am seeing the volunteers collectively focusing crucial bug fixes & refactors currently to get a suitable cabal-browser implementation.

How would a browser implementation work? Would it only work in Beaker at the moment?

**Comment by trosel** [comment]
@nikolaiwarner I see that you have a branch for dark mode already. I'm looking at it on a fork right now. I had issues building the branch because of the fonts though.
![image](https://user-images.githubusercontent.com/57410820/79930603-f141f500-8416-11ea-9cae-cb64cafa7be3.png)


I haven't used `.scss` (or Electron at all) files before, but I usually just use CSS variables. I would normally replace most colors in the main css file with variables, then create a `light.css` and a `dark.css` file which contain the variable definitions for the themes. 

Let me know if you're almost done or if you'd like help with this. I'm unsure of what the fonts were for.

**Comment by nikolaiwarner** [comment]
hi @trosel! Yep! However, I've paused work on this for the moment to do a much bigger refactor of the frontend so that we can use the same components for a browser based version as well as on the electron client. In that, I've switched to using `styled-components` so styling things will be much different. But it's going to make theming and adding dark mode much easier than how i was hacking on this.

Once I get a properly working version of the refactor done, I'd love help with adding theming and dark mode! You can see where it's headed over here: https://github.com/cabal-club/cabal-ui

**Comment by trosel** [comment]
@nikolaiwarner good timing. I'm finally looking into react now haha. Just ping this thread when it's ready 👍

**Comment by nikolaiwarner** [comment]
i added dark mode in the 5.1.0 release! surprise!

later this year we'll get closer to having more full featured theming. but this is a nice thing to have in the meantime!
