### ISSUE TITLE
Implement markdown syntax and styling in messages

### ISSUE THREAD

**Issue by nikolaiwarner** [cabal-club/cabal-desktop#57]

**Comment by callil** [comment]
if we do this - what effect will it have on the cli?

Do we need to add another field to the messages object that's something like `message.richText` ?

@noffle @cblgh

**Comment by nikolaiwarner** [comment]
I'm not sure... markdown doesnt look _too_ bad when unrendered. :D

Really we probably only want a subset of markdown anyhow .... bold, italic, strikethrough ... maybe that's all. And the cli could render that ok.

A codeblock would be nice too... but that would take a little more work on the cli.

**Comment by cblgh** [comment]
yeah the cli can have a parser that, at its most basic, strips out the markdown (could be implemented in [cabal-client](https://github.com/cabal-club/cabal-client/))

@noffle what are your opinions? has ssb had any discussions/issues in markdown-land?

in rotonde we had formatted links, which i thought was really nice. i think the following subset is nice and expressive
- [ ] **bold**
- [ ] _italic_
- [ ] ~strikethrough~
- [ ] `code comment`
- [ ] [formatted links](https://github.com/cabal-club/cabal-desktop/issues/57)

**Comment by noffle** [comment]
@cblgh In scuttlebutt all messages of type `post` are assumed to be in markdown.

I think markdown is a pretty widely accepted part of the web, and am +1 on interpreting all `chat/message` message types as being markdown encoded.

+1 on having the terminal client do its best effort to render the markdown. We could also surface options around this e.g. to render messages as uninterpreted plaintext.

We could use a custom markdown parser, like [ssb-markdown](https://github.com/ssbc/ssb-markdown), in order to include emoji parsing.
